on: [push, workflow_dispatch]

env:
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Create a package called @${{ github.repository }}
      - run: |
          echo `{
            "name": "@jcansdale-test/npm-publish-with-bin",
            "version": "1.0.0",
            "description": "Example publishing an npm package.",
            "main": "index.js",
            "scripts": {
              "test": "echo \"Error: no test specified\" && exit 1"
            },
            "repository": {
              "type": "git",
              "url": "git+https://github.com/jcansdale-test/npm-publish-with-bin.git"
            },
            "keywords": [],
            "author": "",
            "license": "ISC",
            "bugs": {
              "url": "https://github.com/jcansdale-test/npm-publish-with-bin/issues"
            },
            "homepage": "https://github.com/jcansdale-test/npm-publish-with-bin#readme"
          }` > package.json

      - name: Add index.js to package
        run: echo 'exports.sayHello = () => { console.log("Hello from ${{ github.repository }}!") }' > index.js

      - name: Set package version to ${{ env.VERSION }}
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Build the package
        run: npm pack

      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Trigger npm-install workflow
        if: ${{ env.GITHUB_TOKEN != null }}
        run: gh api repos/${{ github.repository_owner }}/npm-install/dispatches <<< '{"event_type":"build"}' --input -
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
